### ISSUE TITLE
sass install error when setting up for local files

### ISSUE THREAD

**Issue by chreman** [OpenKnowledgeMaps/Headstart#200]
while trying to run `npm install` following error occured:
```
> node-sass@3.13.1 install /home/chris/projects/Headstart/node_modules/node-sass
> node scripts/install.js


/home/chris/projects/Headstart/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/chris/projects/Headstart/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! node-sass@3.13.1 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.0-116-generic
npm ERR! command "/home/chris/.nvm/v0.10.40/bin/node" "/home/chris/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /home/chris/projects/Headstart
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by chreman** [comment]
Looks like the error was on my side - my system defaulted back to an old version of npm.
was fixed after I did `nvm use 5.x.x`
